name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Go set up
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.7'
        cache-dependency-path: src/go.sum

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60
        working-directory: ./src 

    - name: Install dependencies
      run: go mod download
      working-directory: ./src

    - name: Build
      run: go build -v ./...
      working-directory: ./src

    - name: Run Unit Tests
      run: go test -v ./...
      working-directory: ./src

  push_image:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Pull repo code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: milosztemp/chatapp:latest, milosztemp/chatapp:${{ github.sha }}